#include <sentinel-cxx.h>  // Generated by cbindgen
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK_ERROR(func_call) \
    do { \
        sentinel_error_t result = (func_call); \
        if (result != SENTINEL_OK) { \
            const char* error = sentinel_get_last_error(); \
            fprintf(stderr, "Error at %s:%d: %s\n", __FILE__, __LINE__, error); \
            sentinel_string_free(error); \
            exit(1); \
        } \
    } while(0)

#define CHECK_NULL(ptr, msg) \
    do { \
        if (!(ptr)) { \
            const char* error = sentinel_get_last_error(); \
            fprintf(stderr, "Error at %s:%d: %s - %s\n", __FILE__, __LINE__, msg, error ? error : "Unknown"); \
            if (error) sentinel_string_free(error); \
            exit(1); \
        } \
    } while(0)

int main() {
    printf("Cyberpath Sentinel C API Example\n");
    printf("=================================\n\n");

    // Create a store
    printf("Creating store at './example_db'...\n");
    sentinel_store_t* store = sentinel_store_new("./example_db", NULL);
    CHECK_NULL(store, "Failed to create store");

    // Create users collection
    printf("Getting 'users' collection...\n");
    sentinel_collection_t* users = sentinel_store_collection(store, "users");
    CHECK_NULL(users, "Failed to get users collection");

    // Insert some users
    printf("Inserting users...\n");

    CHECK_ERROR(sentinel_collection_insert(users, "user1",
        "{\"name\": \"Alice Johnson\", \"email\": \"alice@example.com\", \"age\": 28, \"active\": true}"));

    CHECK_ERROR(sentinel_collection_insert(users, "user2",
        "{\"name\": \"Bob Smith\", \"email\": \"bob@example.com\", \"age\": 34, \"active\": false}"));

    CHECK_ERROR(sentinel_collection_insert(users, "user3",
        "{\"name\": \"Charlie Brown\", \"email\": \"charlie@example.com\", \"age\": 25, \"active\": true}"));

    // Get document count
    unsigned int count = 0;
    CHECK_ERROR(sentinel_collection_count(users, &count));
    printf("Users collection now has %u documents\n\n", count);

    // Retrieve and display users
    printf("Retrieving users:\n");
    const char* user_ids[] = {"user1", "user2", "user3"};

    for (int i = 0; i < 3; i++) {
        char* user_data = sentinel_collection_get(users, user_ids[i]);
        if (user_data) {
            printf("  %s: %s\n", user_ids[i], user_data);
            sentinel_string_free(user_data);
        } else {
            printf("  %s: Not found\n", user_ids[i]);
        }
    }
    printf("\n");

    // Update a user
    printf("Updating user1...\n");
    CHECK_ERROR(sentinel_collection_update(users, "user1",
        "{\"name\": \"Alice Cooper\", \"email\": \"alice@example.com\", \"age\": 29, \"active\": true}"));

    // Verify update
    char* updated_user = sentinel_collection_get(users, "user1");
    if (updated_user) {
        printf("Updated user1: %s\n\n", updated_user);
        sentinel_string_free(updated_user);
    }

    // Upsert operations
    printf("Upsert operations:\n");

    // Upsert existing user (should update)
    bool was_insert = false;
    CHECK_ERROR(sentinel_collection_upsert(users, "user2",
        "{\"name\": \"Bob Wilson\", \"email\": \"bob@example.com\", \"age\": 35, \"active\": true}", &was_insert));
    printf("  Upsert user2 (existing): %s\n", was_insert ? "inserted" : "updated");

    // Upsert new user (should insert)
    CHECK_ERROR(sentinel_collection_upsert(users, "user4",
        "{\"name\": \"Diana Prince\", \"email\": \"diana@example.com\", \"age\": 30, \"active\": true}", &was_insert));
    printf("  Upsert user4 (new): %s\n", was_insert ? "inserted" : "updated");

    // Get final count
    CHECK_ERROR(sentinel_collection_count(users, &count));
    printf("Users collection now has %u documents\n\n", count);

    // List all collections
    printf("Listing all collections:\n");
    char* collections_json = sentinel_store_list_collections(store);
    if (collections_json) {
        printf("Collections: %s\n\n", collections_json);
        sentinel_string_free(collections_json);
    }

    // Create another collection
    printf("Creating 'products' collection...\n");
    sentinel_collection_t* products = sentinel_store_collection(store, "products");
    CHECK_NULL(products, "Failed to get products collection");

    // Add some products
    CHECK_ERROR(sentinel_collection_insert(products, "product1",
        "{\"name\": \"Laptop\", \"price\": 999.99, \"category\": \"electronics\"}"));

    CHECK_ERROR(sentinel_collection_insert(products, "product2",
        "{\"name\": \"Book\", \"price\": 19.99, \"category\": \"books\"}"));

    // List collections again
    collections_json = sentinel_store_list_collections(store);
    if (collections_json) {
        printf("Collections after adding products: %s\n\n", collections_json);
        sentinel_string_free(collections_json);
    }

    // Delete a user
    printf("Deleting user3...\n");
    CHECK_ERROR(sentinel_collection_delete(users, "user3"));

    CHECK_ERROR(sentinel_collection_count(users, &count));
    printf("Users collection now has %u documents\n\n", count);

    // Clean up
    sentinel_collection_free(products);
    sentinel_collection_free(users);

    // Delete products collection
    printf("Deleting products collection...\n");
    CHECK_ERROR(sentinel_store_delete_collection(store, "products"));

    // Final collection list
    collections_json = sentinel_store_list_collections(store);
    if (collections_json) {
        printf("Final collections: %s\n", collections_json);
        sentinel_string_free(collections_json);
    }

    sentinel_store_free(store);

    printf("\nExample completed successfully!\n");
    return 0;
}