/* Cyberpath Sentinel C/C++ Bindings */

#ifndef SENTINEL_CXX_H
#define SENTINEL_CXX_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum sentinel_error_t {
    SENTINEL_OK = 0,
    SENTINEL_ERROR_NULL_POINTER = 1,
    SENTINEL_ERROR_INVALID_ARGUMENT = 2,
    SENTINEL_ERROR_IO_ERROR = 3,
    SENTINEL_ERROR_RUNTIME_ERROR = 4,
    SENTINEL_ERROR_JSON_PARSE_ERROR = 5,
    SENTINEL_ERROR_NOT_FOUND = 6,
    SENTINEL_ERROR_TASK_NOT_FOUND = 7,
    SENTINEL_ERROR_TASK_PENDING = 8,
} sentinel_error_t;

typedef struct sentinel_store_t {
    uint8_t _private[0];
} sentinel_store_t;

typedef struct sentinel_collection_t {
    uint8_t _private[0];
} sentinel_collection_t;

typedef struct sentinel_query_t {
    uint8_t _private[0];
} sentinel_query_t;

typedef void (*StoreCallback)(uint64_t task_id, struct sentinel_store_t *result, char *user_data);

typedef void (*ErrorCallback)(uint64_t task_id, const char *error, char *user_data);

typedef void (*CollectionCallback)(uint64_t task_id,
                                   struct sentinel_collection_t *result,
                                   char *user_data);

typedef void (*VoidCallback)(uint64_t task_id, char *user_data);

typedef void (*DocumentCallback)(uint64_t task_id, char *result, char *user_data);

typedef void (*BoolCallback)(uint64_t task_id, bool result, char *user_data);

typedef void (*CountCallback)(uint64_t task_id, uint32_t result, char *user_data);

typedef struct sentinel_document_t {
    uint8_t _private[0];
} sentinel_document_t;

struct sentinel_store_t *sentinel_store_new(const char *path, const char *passphrase);

void sentinel_store_free(struct sentinel_store_t *store);

struct sentinel_collection_t *sentinel_store_collection(struct sentinel_store_t *store,
                                                        const char *name);

enum sentinel_error_t sentinel_store_delete_collection(struct sentinel_store_t *store,
                                                       const char *name);

char *sentinel_store_list_collections(struct sentinel_store_t *store);

void sentinel_collection_free(struct sentinel_collection_t *collection);

enum sentinel_error_t sentinel_collection_insert(struct sentinel_collection_t *collection,
                                                 const char *id,
                                                 const char *json_data);

char *sentinel_collection_get(struct sentinel_collection_t *collection, const char *id);

enum sentinel_error_t sentinel_collection_delete(struct sentinel_collection_t *collection,
                                                 const char *id);

enum sentinel_error_t sentinel_collection_count(struct sentinel_collection_t *collection,
                                                uint32_t *count);

enum sentinel_error_t sentinel_collection_update(struct sentinel_collection_t *collection,
                                                 const char *id,
                                                 const char *json_data);

enum sentinel_error_t sentinel_collection_upsert(struct sentinel_collection_t *collection,
                                                 const char *id,
                                                 const char *json_data,
                                                 bool *was_insert);

struct sentinel_query_t *sentinel_query_new_simple(const char *field, const char *value);

void sentinel_query_free(struct sentinel_query_t *query);

char *sentinel_collection_query(struct sentinel_collection_t *collection,
                                struct sentinel_query_t *query);

char *sentinel_get_last_error(void);

void sentinel_string_free(char *s);

uint64_t sentinel_store_new_async(const char *path,
                                  const char *passphrase,
                                  StoreCallback callback,
                                  ErrorCallback error_callback,
                                  char *user_data);

uint64_t sentinel_collection_new_async(struct sentinel_store_t *store,
                                       const char *name,
                                       CollectionCallback callback,
                                       ErrorCallback error_callback,
                                       char *user_data);

uint64_t sentinel_store_collection_async(struct sentinel_store_t *store,
                                         const char *name,
                                         CollectionCallback callback,
                                         ErrorCallback error_callback,
                                         char *user_data);

uint64_t sentinel_collection_insert_async(struct sentinel_collection_t *collection,
                                          const char *id,
                                          const char *json_data,
                                          VoidCallback callback,
                                          ErrorCallback error_callback,
                                          char *user_data);

uint64_t sentinel_collection_get_async(struct sentinel_collection_t *collection,
                                       const char *id,
                                       DocumentCallback callback,
                                       ErrorCallback error_callback,
                                       char *user_data);

uint64_t sentinel_collection_update_async(struct sentinel_collection_t *collection,
                                          const char *id,
                                          const char *json_data,
                                          VoidCallback callback,
                                          ErrorCallback error_callback,
                                          char *user_data);

uint64_t sentinel_collection_upsert_async(struct sentinel_collection_t *collection,
                                          const char *id,
                                          const char *json_data,
                                          BoolCallback callback,
                                          ErrorCallback error_callback,
                                          char *user_data);

uint64_t sentinel_collection_delete_async(struct sentinel_collection_t *collection,
                                          const char *id,
                                          VoidCallback callback,
                                          ErrorCallback error_callback,
                                          char *user_data);

/**
 * Get the count of documents asynchronously
 */
uint64_t sentinel_collection_count_async(struct sentinel_collection_t *collection,
                                         CountCallback callback,
                                         ErrorCallback error_callback,
                                         char *user_data);

/**
 * Create a new query builder
 * Returns NULL on error
 */
struct sentinel_query_t *sentinel_query_builder_new(void);

/**
 * Add an equality filter to a query
 * Returns 0 on success, error code on failure
 */
enum sentinel_error_t sentinel_query_builder_filter_equals(struct sentinel_query_t *query,
                                                           const char *field,
                                                           const char *json_value);

/**
 * Add a greater than filter to a query
 */
enum sentinel_error_t sentinel_query_builder_filter_greater_than(struct sentinel_query_t *query,
                                                                 const char *field,
                                                                 const char *json_value);

/**
 * Add a less than filter to a query
 */
enum sentinel_error_t sentinel_query_builder_filter_less_than(struct sentinel_query_t *query,
                                                              const char *field,
                                                              const char *json_value);

/**
 * Add a contains filter to a query (for string fields)
 */
enum sentinel_error_t sentinel_query_builder_filter_contains(struct sentinel_query_t *query,
                                                             const char *field,
                                                             const char *substring);

/**
 * Add a greater or equal filter to a query
 */
enum sentinel_error_t sentinel_query_builder_filter_greater_or_equal(struct sentinel_query_t *query,
                                                                     const char *field,
                                                                     const char *json_value);

/**
 * Add a less or equal filter to a query
 */
enum sentinel_error_t sentinel_query_builder_filter_less_or_equal(struct sentinel_query_t *query,
                                                                  const char *field,
                                                                  const char *json_value);

/**
 * Add a starts with filter to a query (for string fields)
 */
enum sentinel_error_t sentinel_query_builder_filter_starts_with(struct sentinel_query_t *query,
                                                                const char *field,
                                                                const char *prefix);

/**
 * Add an ends with filter to a query (for string fields)
 */
enum sentinel_error_t sentinel_query_builder_filter_ends_with(struct sentinel_query_t *query,
                                                              const char *field,
                                                              const char *suffix);

/**
 * Add an in filter to a query (value must be in the provided JSON array)
 */
enum sentinel_error_t sentinel_query_builder_filter_in(struct sentinel_query_t *query,
                                                       const char *field,
                                                       const char *json_array);

/**
 * Add an exists filter to a query
 * exists: 1 for field must exist, 0 for field must not exist
 */
enum sentinel_error_t sentinel_query_builder_filter_exists(struct sentinel_query_t *query,
                                                           const char *field,
                                                           uint32_t exists);

/**
 * Combine two queries with OR logic
 * Creates a new query that matches either the left OR right query
 */
struct sentinel_query_t *sentinel_query_or(struct sentinel_query_t *left,
                                           struct sentinel_query_t *right);

/**
 * Combine two queries with AND logic
 * Creates a new query that matches both the left AND right query
 */
struct sentinel_query_t *sentinel_query_and(struct sentinel_query_t *left,
                                             struct sentinel_query_t *right);

/**
 * Add sorting to a query
 * field: field name to sort by
 * descending: 0 for ascending, non-zero for descending
 */
enum sentinel_error_t sentinel_query_builder_sort(struct sentinel_query_t *query,
                                                 const char *field,
                                                 uint32_t descending);

/**
 * Add limit to a query
 * limit: maximum number of results to return
 */
enum sentinel_error_t sentinel_query_builder_limit(struct sentinel_query_t *query,
                                                  uint32_t limit);

/**
 * Add offset to a query (skip first N results)
 * offset: number of results to skip
 */
enum sentinel_error_t sentinel_query_builder_offset(struct sentinel_query_t *query,
                                                   uint32_t offset);

#endif  /* SENTINEL_CXX_H */
